/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.Login;

import Controller.SalesmanController;
import Dao.ManagerDao;
import Dao.SalesmanDao;
import Model.Employee.Employee;
import View.Admin.AdminDashboardView;
import View.Salesman.SalesmanDashboardView;
import View.Manager.ManagerDashboardView;
import View.MessageNotify.MessageNotify;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.util.Random;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author ADMIN
 */
public class LoginView extends javax.swing.JFrame {

    /**
     * Creates new form LoginView
     */
    public LoginView() {
        initComponents();
        lbCaptcha.setText(createCaptcha());
        setIcon();
        
    }
    private void setIcon(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Resources/Dashboard/Image/logoSmall.png")));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        btnCheckPass = new javax.swing.JCheckBox();
        btnLogin = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbCaptcha = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCaptcha = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ĐĂNG NHẬP");
        setIconImages(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("ĐĂNG NHẬP");
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("TÊN ĐĂNG NHẬP:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("MẬT KHẨU:");

        txtUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnCheckPass.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCheckPass.setText("Hiển Thị Mật Khẩu");
        btnCheckPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckPassActionPerformed(evt);
            }
        });

        btnLogin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLogin.setText("ĐĂNG NHẬP");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        btnLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnLoginKeyPressed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnExit.setText("THOÁT");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        txtPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Dashboard/Image/3T.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("MÃ CAPTCHA:");

        lbCaptcha.setBackground(new java.awt.Color(102, 255, 255));
        lbCaptcha.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("XÁC THỰC:");

        txtCaptcha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCaptcha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCaptchaKeyPressed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Dashboard/Image/Refresh.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLogin, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUser)
                            .addComponent(txtPassword)
                            .addComponent(txtCaptcha)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnCheckPass)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(lbCaptcha, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 18, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnCheckPass)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(lbCaptcha, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCaptcha, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLogin)
                            .addComponent(btnExit)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel5)))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private String createCaptcha(){
        Random random = new Random();
        int length = 7 + (Math.abs(random.nextInt())%3);
        StringBuffer captchaStrBuffer = new StringBuffer();
        for(int i = 0;i<length;i++){
            int baseCharacterNumber = Math.abs(random.nextInt()) %  62;
            int characterNumber = 0;
            if(baseCharacterNumber < 26){
                characterNumber = 65 + baseCharacterNumber;
            }else if(baseCharacterNumber < 52){
                characterNumber = 97 + (baseCharacterNumber - 26);
            }else{
                 characterNumber = 48 + (baseCharacterNumber - 52);
            }
             captchaStrBuffer.append((char)characterNumber);     
        }
        return captchaStrBuffer.toString();
    }
    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        //Không được để trống tên đăng nhập
        if(txtUser.getText().equals("admin") && txtPassword.getText().equals("123456")){
            this.setVisible(false);
            AdminDashboardView adminView = new AdminDashboardView();
            adminView.setVisible(true);
            return;
        }
        if(txtUser.getText().equals("") || txtPassword.getText().equals("")){
            MessageNotify message = new MessageNotify(this,MessageNotify.Type.WARNING,MessageNotify.Location.TOP_CENTER,"Không được để trống tên tài khoản và mật khẩu!!");
            message.showNotification();
            return;
        }
        SalesmanDao salesmanData = new SalesmanDao();
        ManagerDao managerData = new ManagerDao();
        Employee employeeSales = salesmanData.findAccount(txtUser.getText(),txtPassword.getText());
        Employee employeeManager = managerData.findAccount(txtUser.getText(),txtPassword.getText());
        if(employeeSales.getTaiKhoan().equals("a") && employeeSales.getMatKhau().equals("a") && employeeManager.getTaiKhoan().equals("a") && employeeManager.getMatKhau().equals("a")){
            MessageNotify message = new MessageNotify(this,MessageNotify.Type.WARNING,MessageNotify.Location.TOP_CENTER,"Nhân Viên nhập sai tài khoản hoặc mật khẩu!!");
            message.showNotification();
            return;
        }
        if(!employeeSales.getTaiKhoan().equals("a") && !employeeSales.getMatKhau().equals("a") && employeeSales.getChucVu() == 1){
            this.setVisible(false);
            SalesmanDashboardView salesmanView = new SalesmanDashboardView(employeeSales);
            salesmanView.setVisible(true);
            return;
        }
        if(!employeeManager.getTaiKhoan().equals("a") && !employeeManager.getTaiKhoan().equals("a") && employeeManager.getChucVu() == 2){
            this.setVisible(false);
            ManagerDashboardView managerView = new ManagerDashboardView(employeeManager);
            managerView.setVisible(true);
            return;
        }
        
        //Tên đăng nhập chỉ được chứa số và chữ cái
//        if(!Pattern.matches("^[a-zA-Z0-9]+$",txtUser.getText())){
//            JFrame a = new JFrame();
//             if(JOptionPane.showConfirmDialog(a,"Tên Đăng Nhập chỉ được chứa chữ cái và số!!" , "THÔNG BÁO", JOptionPane.YES_OPTION) == JOptionPane.YES_OPTION){
//                a.setVisible(false);
//            }
//             return;
//        }
        
        
        //Kiểm tra tài khoản mật khẩu theo từng chức vụ
//        if(txtCaptcha.getText().equals(lbCaptcha.getText())){
//            this.setVisible(false);
//            ManagerDashboardView manager = new ManagerDashboardView();
//            manager.setVisible(true);
//            return;
//        }
//         if(txtCaptcha.getText().equals(lbCaptcha.getText()) && txtUser.getText().equals("admin")&& txtPassword.getText().equals("123456")){
//            this.setVisible(false);
//            AdminDashboardView admin = new AdminDashboardView();
//            admin.setVisible(true);
//            return;
//        }
//        if(txtCaptcha.getText().equals(lbCaptcha.getText()) && txtUser.getText().equals("1") && txtPassword.getText().equals("3")){
//            this.setVisible(false);
//            //SalesmanDashboardView employee = new SalesmanDashboardView();
//            //employee.setVisible(true); 
//            return;
//        }
//        //Sai Tài khoản Mật Khẩu hoặc captcha
//        if (!txtCaptcha.getText().equals(lbCaptcha.getText())) {
//            MessageNotify b = new MessageNotify(this,MessageNotify.Type.WARNING,MessageNotify.Location.TOP_CENTER,"Sai Captcha, Vui Lòng Nhập Lại!!");
//            b.showNotification();
//            lbCaptcha.setText(createCaptcha());
//            return;
//        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnCheckPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckPassActionPerformed
        if(btnCheckPass.isSelected()){
            txtPassword.setEchoChar((char)0);
        }else{
            txtPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_btnCheckPassActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        LoginView login= new LoginView();
        login.setVisible(false);
        if(JOptionPane.showConfirmDialog(login,"Bạn có chắc chắc muốn thoát!" , "THOÁT", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        lbCaptcha.setText(createCaptcha());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnLoginKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(txtUser.getText().equals("admin") && txtPassword.getText().equals("123456")){
                this.setVisible(false);
                AdminDashboardView adminView = new AdminDashboardView();
                adminView.setVisible(true);
                return;
            }
            if(txtUser.getText().equals("") || txtPassword.getText().equals("")){
                MessageNotify message = new MessageNotify(this,MessageNotify.Type.WARNING,MessageNotify.Location.TOP_CENTER,"Không được để trống tên tài khoản và mật khẩu!!");
                message.showNotification();
                return;
            }
            SalesmanDao salesmanData = new SalesmanDao();
            ManagerDao managerData = new ManagerDao();
            Employee employeeSales = salesmanData.findAccount(txtUser.getText(),txtPassword.getText());
            Employee employeeManager = managerData.findAccount(txtUser.getText(),txtPassword.getText());
            if(employeeSales.getTaiKhoan().equals("a") && employeeSales.getMatKhau().equals("a") && employeeManager.getTaiKhoan().equals("a") && employeeManager.getMatKhau().equals("a")){
                MessageNotify message = new MessageNotify(this,MessageNotify.Type.WARNING,MessageNotify.Location.TOP_CENTER,"Nhân Viên nhập sai tài khoản hoặc mật khẩu!!");
                message.showNotification();
                return;
            }
            if(!employeeSales.getTaiKhoan().equals("a") && !employeeSales.getMatKhau().equals("a") && employeeSales.getChucVu() == 1){
                this.setVisible(false);
                SalesmanDashboardView salesmanView = new SalesmanDashboardView(employeeSales);
                salesmanView.setVisible(true);
                return;
            }
            if(!employeeManager.getTaiKhoan().equals("a") && !employeeManager.getTaiKhoan().equals("a") && employeeManager.getChucVu() == 2){
                this.setVisible(false);
                ManagerDashboardView managerView = new ManagerDashboardView(employeeManager);
                managerView.setVisible(true);
                return;
            }
        }
    }//GEN-LAST:event_btnLoginKeyPressed

    private void txtCaptchaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCaptchaKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(txtUser.getText().equals("admin") && txtPassword.getText().equals("123456")){
                this.setVisible(false);
                AdminDashboardView adminView = new AdminDashboardView();
                adminView.setVisible(true);
                return;
            }
            if(txtUser.getText().equals("") || txtPassword.getText().equals("")){
                MessageNotify message = new MessageNotify(this,MessageNotify.Type.WARNING,MessageNotify.Location.TOP_CENTER,"Không được để trống tên tài khoản và mật khẩu!!");
                message.showNotification();
                return;
            }
            SalesmanDao salesmanData = new SalesmanDao();
            ManagerDao managerData = new ManagerDao();
            Employee employeeSales = salesmanData.findAccount(txtUser.getText(),txtPassword.getText());
            Employee employeeManager = managerData.findAccount(txtUser.getText(),txtPassword.getText());
            if(employeeSales.getTaiKhoan().equals("a") && employeeSales.getMatKhau().equals("a") && employeeManager.getTaiKhoan().equals("a") && employeeManager.getMatKhau().equals("a")){
                MessageNotify message = new MessageNotify(this,MessageNotify.Type.WARNING,MessageNotify.Location.TOP_CENTER,"Nhân Viên nhập sai tài khoản hoặc mật khẩu!!");
                message.showNotification();
                return;
            }
            if(!employeeSales.getTaiKhoan().equals("a") && !employeeSales.getMatKhau().equals("a") && employeeSales.getChucVu() == 1){
                this.setVisible(false);
                SalesmanDashboardView salesmanView = new SalesmanDashboardView(employeeSales);
                salesmanView.setVisible(true);
                return;
            }
            if(!employeeManager.getTaiKhoan().equals("a") && !employeeManager.getTaiKhoan().equals("a") && employeeManager.getChucVu() == 2){
                this.setVisible(false);
                ManagerDashboardView managerView = new ManagerDashboardView(employeeManager);
                managerView.setVisible(true);
                return;
            }
        }
    }//GEN-LAST:event_txtCaptchaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try{
                    UIManager.setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel");
                }catch(Exception e){
                    e.printStackTrace();
                }
                
                LoginView login = new LoginView();
                login.setVisible(true);
                login.setLocationRelativeTo(null);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox btnCheckPass;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbCaptcha;
    private javax.swing.JTextField txtCaptcha;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
