/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package View.Notification;

import Controller.NotificationController;
import java.awt.Toolkit;

/**
 *
 * @author ADMIN
 */
public class NotificationManagers extends javax.swing.JPanel {

    /** Creates new form NotificationManagers */
    public NotificationManagers() {
        initComponents(); 
        excuteForManager();
    }
    public NotificationManagers(int branch) {
        initComponents();
        excuteForSalesman(branch);
    }
    NotificationController controller = new NotificationController();
    private void excuteForManager(){
        controller.showListNotificationForAdminToCustom(menusNotification);
    } 
    private void excuteForSalesman(int branch){
        controller.showListNotificationForManagerToCustom(menusNotification,branch);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        menusNotification = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(631, 50));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Dashboard/Image/bell.png"))); // NOI18N
        jLabel1.setText("Quản Lý Thông Báo");
        jPanel1.add(jLabel1);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.BorderLayout());

        menusNotification.setLayout(new javax.swing.BoxLayout(menusNotification, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(menusNotification);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel menusNotification;
    // End of variables declaration//GEN-END:variables

}
